kiali/helm-charts

kiali-operator/templates/deployment.yaml, kiali-operator/values.yaml
My use case is the following: kiali operator is deployed behind a proxy that limits access to outside, so I need to be able to add the HTTPS_PROXY environment variable to check the latest version of Kiali on github.
=> Add env customization in pod template

kiali-server/templates/_helpers.tpl, kiali-server/values.yaml
If the user disabled dashboards, the helm chart will no longer install them. Note that helm will always install the CRD - the crds directory is not templated. So it is always installed.
see https://github.com/kiali/kiali/issues/3285
related operator PR: https://github.com/kiali/kiali-operator/pull/154
=> do not install dashboards if they are disabled

Makefile
Using * inside quotes does not expand to a list of files so older files
from previous runs were not deleted.
=> Fix wildcard usage when deleting files

kiali-operator/templates/deployment.yaml, kiali-operator/values.yaml
This is going to be useful when running molecule tests and we want to see the profiling data. Just pass in `--set debug.enableProfiler=true` when installing via helm.
goes with https://github.com/kiali/kiali/issues/3469 and https://github.com/kiali/helm-charts/pull/20
part of fix for: https://github.com/kiali/kiali/issues/3489
=> Be able to turn on profiler via helm setting.

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
Kiali needs to port-forward against a pod in the mesh in order to get the envoy dump of an specific envoy.
This PR adds the necessary for the helm-charts to add the `post|create` permissions for the `pod/portforward` subresource.
Relates to kiali/kiali#3400
Relates to kiali/kiali-ui#2006
Needs https://github.com/kiali/kiali-operator/pull/213
=> [Proxy-config] Add port-forward permissions

Jenkinsfile
This is to break the main "kiali-release" pipeline (which source is in
https://github.com/kiali/kiali/blob/master/deploy/jenkins-ci/Jenkinsfile)
in order to make it thinner.
Related main repo PR: https://github.com/kiali/kiali/pull/3546
Related kiali/kiali#2895
=> Create pipeline to release Helm charts

Jenkinsfile
When releasing a `minor` version, a replacement is done to Makefiles to set the
version being released. This replacement is missing the "v" character
used in container image tags, leading to a reference to the wrong image
tags in the resulting helm charts.
This is adding the missing "v".
Fixes kiali/kiali#3617
=> Fix bad replacement when releasing

.github/workflows/ci.yml, .travis.yml
Since TravisCI is no longer enabled, use GitHub actions for CI.
=> Restore CI

Makefile
This is to support patch builds.
If you want to build prior to updating the metadata index file, then you must explicitly invoke the build targets.
fixes https://github.com/kiali/kiali/issues/3687
=> Do not automatically build when doing an update.

kiali-server/templates/deployment.yaml
On Helm v3 I'm unable to use the chart with metrics_enabled="true" . 
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Deployment.spec.template.metadata.annotations.prometheus.io/port`
=> Helm v3 expects a default value for all keys

kiali-server/templates/service.yaml
Replicating changes of kiali/kiali-operator#264
Testing with these commands and visually checking the resulting YAML:
```bash
helm template kiali-test ./kiali-server
helm template --debug --set server.web_fqdn=example.com kiali-test ./kiali-server
helm template --debug --set server.web_schema=https kiali-test ./kiali-server
helm template --debug --set server.web_fqdn=example.com --set server.web_schema=https kiali-test ./kiali-server
helm template --debug --set server.web_fqdn=example.com --set server.web_schema=https kiali-test --set server.web_root=/foo ./kiali-server
helm template --debug --set server.web_fqdn=example.com --set server.web_schema=https kiali-test --set server.web_root=/foo --set server.web_port=55 ./kiali-server
```
Related to kiali/kiali#3526
=> Annotate Kiali Service with external URL settings

kiali-operator/templates/deployment.yaml
I was using this as part of debugging https://github.com/kiali/kiali/issues/3892 - but this can be merged independent of that.
When you enable the profiler, show the top 100 tasks, not just the default 20
=> be able to customize the length of the ansible profile report

kiali-server/templates/ingress.yaml
Counterpart of https://github.com/kiali/kiali-operator/pull/298
Test 1: `helm template kiali-test ./kiali-server`
Generates:
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
name: kiali
namespace: default
labels:
helm.sh/chart: kiali-server-0.0.0
app: kiali
app.kubernetes.io/name: kiali
app.kubernetes.io/instance: kiali-test
version: "${HELM_IMAGE_TAG}"
app.kubernetes.io/version: "${HELM_IMAGE_TAG}"
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/part-of: "kiali"
annotations:
nginx.ingress.kubernetes.io/secure-backends: "false"
nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
rules:
- http:
paths:
- path: /kiali
backend:
serviceName: kiali
servicePort: 20001
...
```
Test 2: `helm template --set server.web_fqdn=example.com kiali-test ./kiali-server` …
=> Add host stanza to Ingress

kiali-server/templates/_helpers.tpl, kiali-server/templates/configmap.yaml, kiali-server/templates/dashboards/envoy.yaml, kiali-server/templates/dashboards/go.yaml, kiali-server/templates/dashboards/kiali.yaml, kiali-server/templates/dashboards/micrometer-1.0.6-jvm-pool.yaml, kiali-server/templates/dashboards/micrometer-1.0.6-jvm.yaml, kiali-server/templates/dashboards/micrometer-1.1-jvm.yaml, kiali-server/templates/dashboards/microprofile-1.1.yaml, kiali-server/templates/dashboards/microprofile-x.y.yaml, kiali-server/templates/dashboards/nodejs.yaml, kiali-server/templates/dashboards/quarkus.yaml, kiali-server/templates/dashboards/springboot-jvm-pool.yaml, kiali-server/templates/dashboards/springboot-jvm.yaml, kiali-server/templates/dashboards/springboot-tomcat.yaml, kiali-server/templates/dashboards/thorntail.yaml, kiali-server/templates/dashboards/tomcat.yaml, kiali-server/templates/dashboards/vertx-client.yaml, kiali-server/templates/dashboards/vertx-eventbus.yaml, kiali-server/templates/dashboards/vertx-jvm.yaml, kiali-server/templates/dashboards/vertx-pool.yaml, kiali-server/templates/dashboards/vertx-server.yaml, kiali-server/values.yaml
fixes: https://github.com/kiali/kiali/issues/4018
This only touches the kiali-server helm chart.
If you leave all defaults as-is, this works as before and you will not notice any differences. The only difference is if you want to set `fullnameOverride`.
To simulate the way the operator works, the kiali-server helm chart now uses `deployment.instance_name` rather than the now-deprecated `fullnameOverride`. For backwards compatibility, if `fullnameOverride` is not `kiali` but `deployment.instance_name` remains its default value of `kiali`, then `fullnameOverride` is used, otherwise `deployment.instance_name` is used. The old `nameOverride` is deprecated and now ignored.
A second commit in this PR merely removes the quotes from the dashboard apiVersion fields for consistency to all other …
=> [helm] set app.kubernetes.io/instance label appropriately, define the new deployment.instance_name value

Jenkinsfile
When releasing a `minor`, the process was creating a version branch of
the form `x.y` (without a `v` prefix).
That's problematic, because all code assumes the `v` prefix. Releasing a
patch was failing and manual intervention was needed.
This adds the missing `v` prefix.
Fixes kiali/kiali#4010
=> Fix release process: version branch name

kiali-server/templates/dashboards/kiali.yaml
Part of: [#3244](https://github.com/kiali/kiali/issues/3244)
This PR updates the Kiali monitoring dashboard to support:
- API failures metric
- Graph generation duration metric
Also removes the functions related metrics with the motivation of simplify the metrics exposed to users.
=> Kiali monitoring dashboard updated to support new metrics

kiali-server/templates/ingress.yaml
fixes: https://github.com/kiali/kiali/issues/3706
To test, first build with `make build-helm-charts` and then run `helm template -n istio-system kiali-server _output/charts/kiali-server-1.36.0-SNAPSHOT.tgz` and look at the generated Ingress and see that it is using the appropriate api_version for your cluster (it will probably use the v1). You could also install it via `helm install -n istio-system kiali-server _output/charts/kiali-server-1.36.0-SNAPSHOT.tgz`
=> Fix the Ingress apiVersion so it isn't a deprecated version.

kiali-server/templates/deployment.yaml
For Kubernetes, it is marked as optional. For OpenShift, it is still
mandatory.
Related operator PR: https://github.com/kiali/kiali-operator/pull/333
Related kiali/kiali#4050
=> Always mount the kiali-cabundle volume/configmap

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
needs https://github.com/kiali/kiali/pull/4108
There is no need to communicate with Istiod pods using the pod/proxy. Kubernetes assigns a PodIP accessible from all nodes of a cluster.
=> No need for pods/proxy subresource so far

kiali-operator/templates/clusterrole.yaml
part of fix for: https://github.com/kiali/kiali/issues/3241
Do NOT merge until we can first merge https://github.com/kiali/kiali-operator/pull/307 (read the description to see what we are waiting for - basically we need community.kubernetes collection v.1.1+) _UPDATE: we can merge this now_
=> add true can-i check to make sure the operator has the permissions it needs

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/ingress.yaml
Kubernetes version 1.18 `networking.k8s.io/v1` only manages `networkpolicies`. 
`Ingress` are still `networking.k8s.io/v1beta1` until 1.19+
This change ensures  Ingress exists in v1, else use v1beta1 logic.
```
kubectl version --short
Client Version: v1.21.3
Server Version: v1.18.20-eks-8c579e
```
```
kubectl get --raw /apis/networking.k8s.io/v1 | jq .
{
"kind": "APIResourceList",
"apiVersion": "v1",
"groupVersion": "networking.k8s.io/v1",
"resources": [
{
"name": "networkpolicies",
"singularName": "",
"namespaced": true,
"kind": "NetworkPolicy",
"verbs": [
"create",
"delete",
"deletecollection",
"get",
"list",
"patch",
"update",
"watch"
],
"shortNames": [
"netpol"
],
"storageVersionHash": "YpfwF18m1G8="
}
]
}
```
Related to [kubernetes issue …
=> Check Ingress is managed by networking.k8s.io/v1

kiali-server/templates/role-controlplane.yaml, kiali-server/templates/rolebinding-controlplane.yaml, kiali-server/values.yaml
For now, this flag is only allowing or preventing creation of a role and
a rolebinding that grants privileges for reading some secrets in the
Istio namespace. There is no effect on Kiali server side, because it is
failing gracefully. In case it's needed later, this flag is being passed
to Kiali in its ConfigMap.
Default value is `true` for backwards compatibility.
Related kiali/kiali#4147
=> Add feature flag for clustering/federation

kiali-operator/templates/deployment.yaml, kiali-operator/values.yaml, kiali-server/templates/deployment.yaml, kiali-server/values.yaml
fixes https://github.com/kiali/kiali/issues/4392
=> support image digests for disconnected environments

kiali-server/templates/_helpers.tpl, kiali-server/templates/deployment.yaml, kiali-server/templates/service.yaml
If a ConfigMap changes that does not trigger re-deployment of Kiali Server. 
Since the ConfigMap is used for configuring Kiali Server the "rebooting" the Server is required. 
Adding the annotation of kind
`checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}`
helps to force performing rollout of deployment and re-create the pod with Kiali Server.
=> Add annotation in case of changing ConfigMap

kiali-server/templates/_helpers.tpl, kiali-server/templates/configmap.yaml, kiali-server/values.yaml
This PR adds a new property for Istio, the root namespace (https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/).
If it is not configured it defaults to the namespace where Kiali is installed (usually istio-system), same logic from istio_namespace property.
=> Add root namespace property into Kiali config map

kiali-server/templates/deployment.yaml, kiali-server/values.yaml
part of: https://github.com/kiali/kiali/issues/4468
=> support mounting custom secrets in the kiali pod

kiali-operator/values.yaml, kiali-server/templates/ingress.yaml, kiali-server/templates/route.yaml, kiali-server/values.yaml
fixes https://github.com/kiali/kiali/issues/4485
=> implement some best practices

kiali-server/templates/configmap.yaml, kiali-server/values.yaml
Ignoring by default KIA1201 that relates to workload not covered by any auth policy. 
This is for [#4409](https://github.com/kiali/kiali/pull/4409).
The motivation for this is that is pretty common for some workloads to not have an Authorization Policy associated with them. So to avoid filling the UI with errors, we decided to make this validation optional.
=> Ignore workload validation by default

kiali-server/values.yaml
autoscaling API version `v2beta2` is being removed in newer clusters. Default the server helm chart to `v2`.
If you are running an older cluster that does not have `v2`, simply set this value to the `v2beta2` version at the same time you are define the `spec` for the HPA.
Part of: https://github.com/kiali/kiali/issues/5022
=> [helm] Update the HPA api version to be used by default in the server helm chart

.github/workflows/release.yml
This is needed for the git commands to work. Something changed with the checkout action apparently (a very similar thing occured with the kiali.io pipeline before).
=> Add a fetch depth of 0 to GH action checkout

.github/workflows/release.yml
For patch releases, the PR target should be master, not the release branch (ie v1.50).
The following PR is a test on my fork, seems to be correct:
https://github.com/leandroberetta/helm-charts/pull/10/files
=> Patch release create PR targetting master now

.github/workflows/release.yml
Today after GH unstability I see that the first scheduled run would have been failed due to this problem when pipeline is triggered by a scheduled cron.
This is not happening when is run manually, this PR is fixing this situation.
=> Fix release_type variable on next version calculation when scheduled

.github/workflows/release.yml
Similar to the fix in the operator, although this wasn't an issue, because in the absence of the value, it uses the default branch (master), but it's better to have a value just in case if in the future GH Actions implements some change in this behavior.
=> Set release branch in case of no manual input

kiali-operator/templates/kiali-cr.yaml, kiali-operator/values.yaml
This would allow specifying custom annotations on the kiali cr when it is created by the chart. I specifically need this so that I can tell Argo CD to have it in a later sync wave so during a delete operation the cr is removed before the operator.
(updated by @jmazzitelli July 8, 2022)
fixes: https://github.com/kiali/kiali/issues/5297
=> feat: allow custom annotations on kiali cr

kiali-operator/templates/deployment.yaml, kiali-server/templates/deployment.yaml
part of https://github.com/kiali/kiali/issues/5399
=> security context - drop all capabilities

Makefile
fixes: https://github.com/kiali/kiali/issues/5580
=> Fix for Apple MacOS M1

kiali-operator/templates/deployment.yaml
fixes: https://github.com/kiali/kiali/issues/5949 [added by @jmazzitelli]
By default `metrics.enabled` set to `true`, this adds annotation `prometheus.io/scrape: true`. However there no annotations that describe what port and endpoint needs to be used:
```
prometheus.io/path: /metrics
prometheus.io/port: "8080"
```
If `kiali-operator` deployed with istio sidecar - sidecar trying to scrap applications metrics from default port `80`.
This triggers errors like this:
```
2023-03-25T22:34:09.768729Z	error	failed scraping application metrics: error scraping http://localhost:80/metrics: Get "http://localhost:80/metrics": dial tcp [::1]:80: connect: connection refused
```
To fix it - need to add annotations for `Deployment`:
```
prometheus.io/path: /metrics
prometheus.io/port: "8080"
```
You can …
=> Fix parameters from metrics scraping by prometheus

kiali-server/templates/rolebinding.yaml
Prior to this change, the post installation update of the kiali-server helm chart value deployment.view_only_mode fails as it tries to change the roleRef which is immutable. This change tries to create a new clusterrolebinding based on the view_only_mode configuration.
Fixes https://github.com/kiali/kiali/issues/6139
=> Support for updation of kiali-server helm value view_only_mode

kiali-operator/Chart.yaml, kiali-server/Chart.yaml
we've been releasing the helm charts with a broken icon. This is a minor issue, but would be nice if we publish future charts that point to an existing icon.
=> fix icon link in the helm charts metadata

kiali-operator/crds/crds.yaml, kiali-operator/templates/clusterrole.yaml, kiali-operator/templates/deployment.yaml, kiali-operator/templates/ossmconsole-crd.yaml
part of: https://github.com/kiali/kiali/issues/6790
=> Provide different OpenShift and non-OpenShift watches yaml files

hack/smoke-test-release-branch.sh
This is what the action output will look like when the smoke test passes:
https://github.com/jmazzitelli/helm-charts/actions/runs/6693245429/job/18183991274?pr=3#step:3:83
This is what the action output will look like when the smoke test fails:
https://github.com/jmazzitelli/helm-charts/actions/runs/6693193706/job/18183839296?pr=3#step:3:84
=> check that the plugin image (version the same as the server) is published on quay

.github/workflows/release.yml
If it fails, title the PR with a loud warning and indicate it should not be merged. Otherwise, create the PR as it normally does.
fixes https://github.com/kiali/kiali/issues/6704
=> have the release workflow run the smoketest.

kiali-operator/templates/deployment.yaml, kiali-operator/values.yaml
resolves kiali/kiali#6888
1. Mount emptyDir to /tmp instead of /tmp/ansible-operator/runner 
2. Define ANSIBLE_LOCAL_TEMP env variable to set path for Ansible temporary directory to /tmp/ansible/tmp instead of root filesystem. 
3. Create localAnsibleTmpPath in Values so users can set their own path.
4. Set readOnlyRootFilesystem to true in operator deployment.yaml to enable this feature by default.
=> Add support for read-only root filesystem and enable by default

kiali-server/values.yaml
Issue https://github.com/kiali/kiali/issues/6665
Original feature: https://github.com/kiali/kiali/issues/1567
Make sure that in helm installation the "additional_display_details" a set, similar to operator one: https://github.com/kiali/kiali-operator/blob/master/crd-docs/cr/kiali.io_v1alpha1_kiali.yaml#L8
=> Added additional_display_details to be default set.

kiali-server/values.yaml
Metrics default fields should fall under [observability](https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.server.observability.metrics).
=> Fix default server metrics settings

kiali-server/templates/_helpers.tpl, kiali-server/templates/deployment.yaml, kiali-server/values.yaml
Adds a top level `clustering` field to the kiali spec.
Relates to kiali/kiali#6243
=> Add top level `clustering` field

.github/workflows/release.yml
We need to add some git configuration back into the pipeline because is required to push or create tags. Current releases failed because of this: https://github.com/kiali/helm-charts/actions/runs/7868923370 
For reference, this is the PR that made the change: https://github.com/kiali/helm-charts/pull/243
For now, until we investigate a way of removing this configuration, we will need it for release.
=> Add git config back

kiali-server/templates/service.yaml, kiali-server/values.yaml
Related Issue ➜ [Kiali Server Helm Chart Support Custom NodePort](https://github.com/kiali/kiali/issues/7093)
When Kiali Server is deployed to hundreds of Kubernetes clusters, it would be very good to have this feature to access all clusters with the same `nodePort`. This PR was prepared to use a custom port for `NodePort`. 
In Values, we can get the nodePort value as follows:
```
server:
port: 20001
nodePort: 32475
observability:
metrics:
enabled: true
port: 9090
nodePort: 32476
web_root: ""
```
We can use it in the Service as follows:
```
{{- if eq .Values.deployment.service_type nodePort }}
nodePort: {{ .Values.server.nodePort }}
{{- end }}
```
#7093
=> feat(kiali-server): add custom nodeport for service

kiali-server/templates/_helpers.tpl
It has been deprecated/superceded since v1.26 (4 years ago)
part of: https://github.com/kiali/kiali/issues/7208
=> remove verbose_mode that has been deprecated

hack/smoke-test-release-branch.sh
part of https://github.com/kiali/kiali/issues/6865
=> comment out the ossmc image check - we will not smoke test it.

kiali-server/templates/deployment.yaml, kiali-server/values.yaml
part of https://github.com/kiali/kiali/issues/7150
To test, just run the `helm template` command to see the different Deployment yaml that can be produced. First make sure you build the helm charts so the PR changes are picked up locally (i.e. `make build-helm-charts`).
1. Set both dns policy and dns config:
```bash
helm template --set deployment.dns.policy="ClusterFirst" --set deployment.dns.config.options[0].name="ndots" --set-string deployment.dns.config.options[0].value="1" --set deployment.dns.config.nameservers[0]="11.22.33.44" --show-only templates/deployment.yaml _output/charts/kiali-server-1.85.0-SNAPSHOT.tgz | yq '.spec.template.spec' | yq eval '. | (.dnsPolicy, .dnsConfig)'
```
results in:
```yaml
ClusterFirst
nameservers:
- 11.22.33.44
options:
- name: ndots
value: "1"
``` …
=> be able to set DNS policy and config on the Kiali pod

kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
PR to solve https://github.com/kiali/kiali/issues/7357
=> fix(kiali-server): don't create unused ClusterRole

kiali-server/templates/deployment.yaml
part of: https://github.com/kiali/kiali/issues/7187
=> do not attempt to mount a cluster secret if none were provided.

kiali-server/templates/deployment.yaml, kiali-server/values.yaml
part of: https://github.com/kiali/kiali/issues/7559
To test this:
1. Create this file (`/tmp/values.yaml`) - note that HPA is defined and an abnormally large value for `deployment.replicas` is set - you will notice that large replicas value won't appear in the generated yaml:
```yaml
deployment:
replicas: 123456
hpa:
spec:
maxReplicas: 6
minReplicas: 3
metrics:
- type: Resource
resource:
name: cpu
target:
type: Utilization
averageUtilization: 70
- type: Resource
resource:
name: memory
target:
type: Utilization
averageUtilization: 70
resources:
requests:
memory: "1Gi"
limits:
memory: "2Gi"
```
2. Check out this PR branch and build the helm charts: `make build-helm-charts`
3. Show the deployment and HPA templates using that values file:
```
helm template -f /tmp/values.yaml --show-only …
```
=> ignore replicas if HPA is set

README.adoc, kiali-operator/templates/clusterrole.yaml, kiali-operator/templates/deployment.yaml, kiali-operator/values.yaml, kiali-server/templates/NOTES.txt, kiali-server/templates/_helpers.tpl, kiali-server/templates/configmap.yaml, kiali-server/values.yaml
part of: kiali/kiali#7546
part of KEP: https://github.com/kiali/kiali/blob/master/design/KEPS/namespace-discovery/proposal.md
server PR: https://github.com/kiali/kiali/pull/7592
operator PR: https://github.com/kiali/kiali-operator/pull/797
helm chart PR: kiali/helm-charts#274
docs PR: https://github.com/kiali/kiali.io/pull/807
=> Removing accessible namespaces as part of the new discovery selector support

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
This is necessary to read tags in the cluster.
=> Grant kiali role list permissions for mutating webhooks

kiali-operator/templates/clusterrolebinding.yaml, kiali-operator/templates/deployment.yaml, kiali-operator/templates/kiali-cr.yaml, kiali-operator/templates/serviceaccount.yaml, kiali-server/templates/cabundle.yaml, kiali-server/templates/configmap.yaml, kiali-server/templates/deployment.yaml, kiali-server/templates/hpa.yaml, kiali-server/templates/ingress.yaml, kiali-server/templates/oauth.yaml, kiali-server/templates/role-controlplane.yaml, kiali-server/templates/rolebinding-controlplane.yaml, kiali-server/templates/rolebinding.yaml, kiali-server/templates/route.yaml, kiali-server/templates/service.yaml, kiali-server/templates/serviceaccount.yaml
part of: https://github.com/kiali/kiali/issues/7773
To test:
1. `make build-helm-charts`
2. `kubectl create ns 12345`
3. `helm install --namespace 12345 kiali-server _output/charts/kiali-server*.tgz`
It should install fine, with no errors from helm. The server won't start because its trying to pull an image that doesn't exist, but that is irrelevant for this issue. We just want to make sure helm does not fail.
You can uninstall with:
```
helm uninstall --namespace 12345 kiali-server
```
1. `make build-helm-charts`
2. `kubectl create ns 12345`
3. `helm install --namespace 12345 --set cr.create=true kiali-operator _output/charts/kiali-operator*.tgz`
It should install fine, with no errors from helm. The operator won't start because its trying to pull an image that doesn't exist, but that is …
=> support namespaces with just numerals in their names

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/smoketest.yml
Currently, github actions use v3 of actions/checkout, which internally runs on Node 16 (https://github.com/actions/checkout/blob/v3/action.yml#L90).
This PR upgrades github actions to v4, which internally runs Node on 20 (https://github.com/actions/checkout/blob/v4/action.yml#L102)
=> Upgrade github actions to Node 20

kiali-server/templates/deployment.yaml, kiali-server/values.yaml
a corporate L7 proxy sits between my kiali deployment and my prometheus server. I need to specify the (HTTP|HTTPS|NO)_PROXY environment variables in my helm chart deployment.
part of: https://github.com/kiali/kiali/issues/7569
=> add support for custom environment variables to the server deployment

.github/workflows/release.yml, Makefile
This PR adds the ability to do major releases.
Schedule runs are disabled for now.
This PR also sets the 2.0 version for the next Kiali major release on next Monday.
=> Add the possiblity to do a major release

Makefile, kiali-operator/templates/_helpers.tpl, kiali-server/templates/_helpers.tpl
1. `app.kubernetes.io/managed-by: Helm` is automatically applied to resources _installed_ by Helm, and does not need to be (read: should not be) manually templated. The label is an install-time label that should be applied by the tool actually installing the resources into the cluster.
This matters because `helm template` should (and by default will) produce YAML without this label, as it is unknown at template-time what will "manage" the resource.
2. Also fix the `makefile` so it doesn't try to download the wrong Helm bin on linux/arm64.
_(@jmazzitelli added the fixes line below)_
fixes: https://github.com/istio/istio/issues/53698
=> Managed-by should only be set by `helm` or similar at install time

kiali-server/templates/_helpers.tpl, kiali-server/templates/cabundle.yaml, kiali-server/templates/deployment.yaml, kiali-server/templates/hpa.yaml, kiali-server/templates/ingress.yaml, kiali-server/templates/oauth.yaml, kiali-server/templates/route.yaml, kiali-server/templates/service.yaml, kiali-server/values.yaml
this refactor the way we determine if it is an OpenShift cluster (for easier testing and maintenance)
part of https://github.com/kiali/kiali/issues/7861
To test quickly run this 4-part command:
```
echo -e "\nK8s full install:\n" && helm template -n istio-system --set deployment.ingress.enabled=true --set isOpenShift=false kiali-server _output/charts/kiali-server-*.tgz | grep "^kind:" && echo -e "\nOpenShift full install\n" && helm template -n istio-system --set deployment.ingress.enabled=true --set auth.openshift.redirect_uris[0]=foo --set isOpenShift=true kiali-server _output/charts/kiali-server-*.tgz | grep "^kind:" && echo -e "\nK8s remote only install:\n" && helm template -n istio-system --set deployment.ingress.enabled=true --set deployment.remote_cluster_resources_only=true --set …
```
=> support remote_cluster_resources_only=true and support redirect_uris for openshift oauthclient

kiali-operator/templates/deployment.yaml, kiali-server/templates/deployment.yaml
1. Defines ` terminationMessagePolicy: FallbackToLogsOnError` for operator and server.
2. Ensures liveness, readiness, and startup probes are defined for operator and server.
This PR goes with the operator PR: https://github.com/kiali/kiali-operator/pull/843
See: https://issues.redhat.com/browse/OSSM-8356
=> make some changes for best practices

kiali-server/templates/deployment.yaml, kiali-server/values.yaml
fixes: https://github.com/kiali/kiali/issues/7832
=> be able to configure server liveness/readiness/startup probe

.github/workflows/release.yml
Now that we have tested the new release GitHub Action and confirmed it works properly, it is time to enable the automated release schedule.
Verify that the github action is correct.
N/A
=> Enable the release schedule in github actions

kiali-operator/templates/deployment.yaml
the default value used to be 8080 but in ansible operator 1.36.0, that default was changed to 8443. So we need to explicitly set it 8080 now.
This goes with operator PR https://github.com/kiali/kiali-operator/pull/857
=> [operator] explicitly set metrics bind address to 8080

kiali-server/templates/deployment.yaml, kiali-server/values.yaml
part of : https://github.com/kiali/kiali/issues/5614
To quickly test:
1. Build the charts: `make build-helm-charts`
2. Set some topology spread constraints to see that it gets into the deployment yaml:
```bash
helm template -n istio-system \
--show-only templates/deployment.yaml \
--set deployment.topology_spread_constraints[0].maxSkew=1 \
--set deployment.topology_spread_constraints[0].whenUnsatisfiable=DoNotSchedule \
--set deployment.topology_spread_constraints[0].topologyKey=kubernetes.io/hostname \
kiali-server \
_output/charts/kiali-server-*.tgz
```
3. See that the spec.topologySpreadConstraints yaml is in the yaml
4. Now see that if you do not specify topology spread constraints, the yaml does not show anything:
```
helm template -n istio-system --show-only …
```
=> support topologySpreadConstraints in Deployment config

kiali-server/templates/_helpers.tpl, kiali-server/templates/deployment.yaml
fixes: https://github.com/kiali/kiali/issues/7877
This will always mount secret `kiali-multi-cluster-secret` - but it is optional. If the secret doesn't exist, the server will still start.
The secret does not need to be labeled  - it simply needs to have its name be "kiali-multi-cluster-secret"
To test, I first created a remote secret using our hack script (my minikube cluster is named "ci"):
```
hack/istio/multicluster/kiali-prepare-remote-cluster.sh -astv false --dry-run true -prr false -kcc current -rcc ci
```
The resulting secret yaml was then modified - I removed the annotation and label and I renamed it "kiali-multi-cluster-secret" - I stored it in a file "secret.yaml". I then "kubectl apply -f secret.yaml -n istio-system" to create the secret.
Then you can run helm install to see …
=> optionally mount secret volume kiali-multi-cluster-secret

kiali-server/values.yaml
Make sure pod_annotations `proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'` is always set to be ready to install Kiali on auto-injection=enabled namespaces.
Issue https://github.com/kiali/kiali/issues/8259
=> Added holdApplicationUntilProxyStarts in pod_annotations
