kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
Adding permissions for fetching proxy-status
Needs https://github.com/kiali/kiali/pull/3126
=> Add pods/proxy resource permissions

Makefile, kiali-operator/templates/clusterrole.yaml, kiali-server/templates/ingress.yaml
fixes: https://github.com/kiali/kiali/issues/3343
=> Use the non-deprecated apiVersion. Also, fix the typo in the filename.

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
Related to https://github.com/kiali/kiali-operator/pull/175
Context:
https://github.com/kiali/kiali/issues/3341
=> Remove Mixer + RBAC deps

kiali-server/templates/deployment.yaml, kiali-server/values.yaml
Addresses issue https://github.com/kiali/kiali/issues/3356
=> Be able to specify labels on the Kiali pod.

kiali-operator/templates/_helpers.tpl, kiali-server/templates/_helpers.tpl
fixes https://github.com/kiali/kiali/issues/3411
=> add some common k8s labels.

.github/kiali.yml
=> Configure kiali-bot to "squash" when merging PRs

kiali-operator/templates/deployment.yaml
this goes with https://github.com/kiali/kiali/issues/3469
=> explicitly define ANSIBLE_CONFIG so an admin can more easily change it

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/hpa.yaml, kiali-server/values.yaml
part of : https://github.com/kiali/kiali/issues/3533
* kiali/kiali PR: https://github.com/kiali/kiali/pull/3542
* operator PR: https://github.com/kiali/kiali-operator/pull/230
* helm-charts PR: https://github.com/kiali/helm-charts/pull/26
=> helm charts/operator now supports creating an HPA resource

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
additional capability for https://github.com/kiali/kiali/issues/3207
=> add tokenreview to support login check for headers

kiali-server/templates/role-controlplane.yaml, kiali-server/templates/rolebinding-controlplane.yaml
Related kiali/kiali#1833
Related kiali/kiali#3409
Related kiali/kiali-operator#235
=> [multi-cluster] Add permissions needed for the "Mesh" page

kiali-server/templates/rolebinding-controlplane.yaml
fixes: https://github.com/kiali/kiali/issues/3667
=> the name of the role being bound to might be different if the user specified fullnameOverride

kiali-operator/crds/crds.yaml, kiali-server/crds/crds.yaml
fixes: https://github.com/kiali/kiali/issues/1757
=> switch to CRD v1

Jenkinsfile
=> Add patch releases support to Jenkins pipeline

kiali-server/templates/dashboards/envoy.yaml
Fixes https://github.com/kiali/kiali/issues/2582
=> Enable envoy dashboards

kiali-operator/templates/deployment.yaml, kiali-operator/templates/kiali-cr.yaml
part of: https://github.com/kiali/kiali/issues/2983
=> Changes necessary to move to Ansible Operator SDK 1.x

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
needs https://github.com/kiali/kiali/pull/3764
=> Allow kiali to consume DaemonSets

kiali-server/templates/dashboards/envoy.yaml, kiali-server/templates/dashboards/go.yaml, kiali-server/templates/dashboards/kiali.yaml, kiali-server/templates/dashboards/micrometer-1.0.6-jvm-pool.yaml, kiali-server/templates/dashboards/micrometer-1.0.6-jvm.yaml, kiali-server/templates/dashboards/micrometer-1.1-jvm.yaml, kiali-server/templates/dashboards/microprofile-1.1.yaml, kiali-server/templates/dashboards/microprofile-x.y.yaml, kiali-server/templates/dashboards/nodejs.yaml, kiali-server/templates/dashboards/quarkus.yaml, kiali-server/templates/dashboards/springboot-jvm-pool.yaml, kiali-server/templates/dashboards/springboot-jvm.yaml, kiali-server/templates/dashboards/springboot-tomcat.yaml, kiali-server/templates/dashboards/thorntail.yaml, kiali-server/templates/dashboards/tomcat.yaml, kiali-server/templates/dashboards/vertx-client.yaml, kiali-server/templates/dashboards/vertx-eventbus.yaml, kiali-server/templates/dashboards/vertx-jvm.yaml, kiali-server/templates/dashboards/vertx-pool.yaml, kiali-server/templates/dashboards/vertx-server.yaml
fixes: https://github.com/kiali/kiali/issues/3812
=> explicitly specify namespace in dashboard yamls

kiali-server/templates/service.yaml
Discussed from https://github.com/kiali/kiali-operator/pull/275#issuecomment-810296550
=> Fix deprecated api link

kiali-operator/templates/deployment.yaml, kiali-operator/values.yaml
OSSM-438
- https://github.com/kiali/kiali/pull/3850
- https://github.com/kiali/kiali-operator/pull/278
=> set the operator env var to indicate if ad hoc kiali namespaces are allowed

kiali-operator/templates/clusterrole.yaml
fixes: https://github.com/kiali/kiali/issues/3854
=> retain the permissions that are still needed for the old supported versions

kiali-operator/templates/deployment.yaml, kiali-operator/values.yaml
fixes: https://github.com/kiali/kiali/issues/3865
=> Be able to disable ad hoc images.

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
fixes https://github.com/kiali/kiali/issues/3877
part of https://github.com/kiali/kiali/issues/3871
needs backend: https://github.com/kiali/kiali/pull/3880
needs operator: https://github.com/kiali/kiali-operator/pull/288
=> Removing HPA permissions

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
fixes: https://github.com/kiali/kiali/issues/3871
fixes: https://github.com/kiali/kiali/issues/3878
Some of these are trivial changes simply to make it easier to perform a diff across the many different files that contain these roles.
=> audit permissions

kiali-server/templates/deployment.yaml
fixes: https://github.com/kiali/kiali/issues/3921
=> fix the affinity value names

kiali-server/templates/deployment.yaml
fixes: https://github.com/kiali/kiali/issues/4023
=> more security to the kiali pod

kiali-operator/templates/deployment.yaml
fixes: https://github.com/kiali/kiali/issues/3918
=> add security to operator pod

kiali-server/templates/route.yaml
part of: https://github.com/kiali/kiali/issues/4255
=> conform to the correct route syntax for target port

kiali-server/templates/route.yaml
part of: https://github.com/kiali/kiali/issues/4255
backport of: https://github.com/kiali/helm-charts/pull/91/files
=> [v1.36] conform to the correct route syntax for target port

Makefile
=> Record that 1.36.2 was released, in preparation for next patch version.

kiali-operator/templates/clusterrole.yaml
fixes: https://github.com/kiali/kiali/issues/4290 (UPDATED by mazz with the correct url)
removing events and pvc
=> removing events and pvc

Makefile
=> Record that 1.36.2 was released, in preparation for next patch version

kiali-operator/templates/clusterrole.yaml, kiali-operator/values.yaml, kiali-server/templates/role-controlplane.yaml, kiali-server/values.yaml
Needed by [#4227](https://github.com/kiali/kiali/pull/4227)
=> Grant permissions to kiali operator SA to read Secrets

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
Related to https://github.com/kiali/kiali/issues/4643
=> Remove Iter8 extension

kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml, kiali-server/values.yaml
part of: https://github.com/kiali/kiali/issues/4737
server PR: https://github.com/kiali/kiali/pull/4839
operator PR: https://github.com/kiali/kiali-operator/pull/507
helm PR: https://github.com/kiali/helm-charts/pull/130
=> provide the ability to disable features

.github/workflows/release.yml
This PR adds the scheduling mechanism on Mondays.
=> Helm charts release schedule

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
Required for [#5274](https://github.com/kiali/kiali/issues/5274)
=> Add extensions and telemetry permissions

kiali-operator/templates/deployment.yaml, kiali-server/templates/deployment.yaml
part of https://github.com/kiali/kiali/issues/5409
=> remove seccompProfile

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
Required by https://github.com/kiali/kiali-operator/pull/569
and https://github.com/kiali/kiali/pull/5345
=> Added K8s Gateway API permissions.

kiali-operator/templates/deployment.yaml, kiali-operator/values.yaml, kiali-server/templates/deployment.yaml, kiali-server/values.yaml
part of: https://github.com/kiali/kiali/issues/5455
Operator PR: https://github.com/kiali/kiali-operator/pull/568
=> be able to supply your own security context for operator and server containers

kiali-operator/templates/deployment.yaml, kiali-operator/values.yaml
operator PR: https://github.com/kiali/kiali-operator/pull/582
helm PR: https://github.com/kiali/helm-charts/pull/175
doc PR: https://github.com/kiali/kiali.io/pull/593
=> support operator config for controlling accessible namespaces

kiali-server/templates/rolebinding.yaml
part of: https://github.com/kiali/kiali/issues/5611
=> kiali SA to be given read-only perms unless using anonymous strategy with view_only_mode off

kiali-server/templates/oauth.yaml
part of: https://github.com/kiali/kiali/issues/5650
PRs that implement this feature:
* https://github.com/kiali/kiali/pull/5652
* https://github.com/kiali/kiali-operator/pull/593
* https://github.com/kiali/helm-charts/pull/183
=> Be able to customize some timeouts for openshift auth

.github/workflows/release.yml
Changed the way the pipeline set outputs from steps.
=> Removed deprecated warning

kiali-server/templates/service.yaml
part of: https://github.com/kiali/kiali/issues/5670
operator PR: https://github.com/kiali/kiali-operator/pull/597
=> add appProtocol to Service template

kiali-server/templates/_helpers.tpl, kiali-server/templates/deployment.yaml, kiali-server/templates/role-controlplane.yaml, kiali-server/values.yaml
part of: https://github.com/kiali/kiali/issues/5738
=> remove list secrets perm, mount cluster secrets to file system, support autodiscovery of cluster secrets

CONTRIBUTING.md
part of https://github.com/kiali/kiali/issues/5808
=> CONTRIBUTING.adoc

kiali-server/templates/_helpers.tpl, kiali-server/templates/deployment.yaml, kiali-server/values.yaml
part of: https://github.com/kiali/kiali/issues/5767
=> mount with the subdirectory as the name of the secret, not the cluster

kiali-operator/templates/deployment.yaml, kiali-operator/values.yaml
https://github.com/kiali/kiali/issues/5832
=> Pod labels for Kiali Operator Helm Chart

kiali-operator/templates/clusterrole.yaml
part of: https://github.com/kiali/kiali/issues/6083
=> provide permission to support override_yaml.spec.host on openshift

kiali-server/values.yaml
Operator PR: https://github.com/kiali/kiali-operator/pull/647
=> Fix the correct validation message code to ignore

kiali-server/templates/oauth.yaml
part of https://github.com/kiali/kiali/issues/6180
=> set oauth redirect to route with non-standard port

kiali-operator/crds/crds.yaml, kiali-operator/templates/clusterrole.yaml, kiali-operator/templates/deployment.yaml, kiali-operator/values.yaml
- Kiali: https://github.com/kiali/kiali/pull/6691
- Kiali Operator: https://github.com/kiali/kiali-operator/pull/691
- Helm Charts: https://github.com/kiali/helm-charts/pull/226
- Kiali.io docs: https://github.com/kiali/kiali.io/pull/705
- OSSMC: https://github.com/kiali/openshift-servicemesh-plugin/pull/211
see: https://issues.redhat.com/browse/OSSM-4944
=> support for OSSMC in the Kiali Operator

.github/workflows/release.yml
For why this is being done, see https://github.com/kiali/helm-charts/pull/233#issuecomment-1818981654
=> [github actions] delay release until 8am

.github/workflows/release.yml
Part-of https://github.com/kiali/kiali/issues/6515
=> removed all mentions of kiali-bot

kiali-server/templates/deployment.yaml, kiali-server/templates/service.yaml
=> Use correct helm values for observability metrics

kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
=> Add oauthclient permissions

kiali-server/templates/oauth.yaml
=> Use new auth callback url

.github/workflows/release.yml
Update ubuntu version on GH action
Part of https://github.com/kiali/kiali/issues/8175
=> Update ubuntu version on GH actions

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
Core PR https://github.com/kiali/kiali/pull/8566
=> Added inference.networking.x-k8s.io apiGroup

kiali-operator/crds/crds.yaml
Ref. https://github.com/kiali/kiali-operator/pull/940
=> [Perses] Update operator crds

.github/workflows/release.yml, Makefile, kiali-operator/templates/ossmconsole-crd.yaml
part of: https://github.com/kiali/kiali/issues/8681
this also checks the OSSMC CRD - we weren't doing that before
=> release workflow to validate crd sync

kiali-operator/crds/crds.yaml
=> update CRD schema

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
Core PR https://github.com/kiali/kiali/pull/8663
Issue https://github.com/kiali/kiali/issues/8656
=> Removed project.openshift.io

kiali-operator/crds/crds.yaml, kiali-operator/templates/clusterrole.yaml, kiali-server/templates/networkpolicy.yaml, kiali-server/values.yaml, tests/kiali-server-tests/networkpolicy-custom-both-ports.yaml, tests/kiali-server-tests/networkpolicy-custom-metrics-port.yaml, tests/kiali-server-tests/networkpolicy-custom-name.yaml, tests/kiali-server-tests/networkpolicy-custom-server-port.yaml, tests/kiali-server-tests/networkpolicy-default-enabled.yaml, tests/kiali-server-tests/networkpolicy-default-ports.yaml, tests/kiali-server-tests/networkpolicy-disabled-count.yaml, tests/kiali-server-tests/networkpolicy-metrics-disabled.yaml, tests/kiali-server-tests/networkpolicy-remote-cluster-count.yaml, tests/kiali-server-tests/rbac-no-cluster-wide-access-anonymous.yaml, tests/kiali-server-tests/rbac-no-cluster-wide-access.yaml, tests/kiali-server-tests/skip-resources-cluster-rbac.yaml, tests/kiali-server-tests/skip-resources-serviceaccount.yaml
part of https://github.com/kiali/kiali/issues/8536
this is built on top of PR:
* https://github.com/kiali/helm-charts/pull/327
=> create networkpolicy to restrict ingress to kiali

kiali-operator/crds/crds.yaml
for: https://github.com/kiali/kiali-operator/pull/966
=> sync CRD: workload settings

kiali-operator/templates/clusterrole.yaml, kiali-server/templates/role-viewer.yaml, kiali-server/templates/role.yaml
Core PR https://github.com/kiali/kiali/pull/8783
Issue https://github.com/kiali/kiali/issues/8782
=> K8s GW API Inference Extensions to v1
